name: Docker Deployment
on:
    workflow_run:
        workflows:
            - Docker Build
        types:
            - completed
env:
    REGISTRY: ghcr.io
    USERNAME: ${{ github.actor }}
    PASSWORD: ${{ secrets.GITHUB_TOKEN }}
    IMAGE_NAME: ${{ github.event.repository.name }}
    COMPOSE_CONFIGURATION_FILE: /home/docker-compose.yml
jobs:
    deployment:
        runs-on: self-hosted
        steps:
            - name: Log in to the Container registry
              uses: docker/login-action@v2
              with:
                registry: ${{ env.REGISTRY }}
                username: ${{ env.USERNAME }}
                password: ${{ env.PASSWORD }}
            - name: Pull service image
              run: docker compose -f ${{ env.COMPOSE_CONFIGURATION_FILE }} pull ${{ env.IMAGE_NAME }}
            - name: Create and start containers
              run: docker compose -f ${{ env.COMPOSE_CONFIGURATION_FILE }} up -d ${{ env.IMAGE_NAME }}
            - name: Remove unused data
              run: docker system prune -f
