name: Docker
on:
  push: [main]
env:
  IMAGE_REGISTRY: "ghcr.io"
  FOO_IMAGE_NAME: ${{ github.repository }}/foo
  FOO_IMAGE_VERSION: "v2"
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Log into registry ${{ env.IMAGE_REGISTRY }}
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: publish
        uses: 0x4r45h/docker-compose-ci@v0.1.0
